### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by MichaelCurrin** [atapas/princess-finder#3]
```diff
-This app was built as part of the Hasnode's
+This app was built as part of the HashNode's
```

**Comment by atapas** [comment]
Hi @MichaelCurrin,

Great catch. Yep, it should be `Hashnode`. I shall fix it up soon. Btw... Feel free to pick it up for a fix if you would like to.

**Comment by atapas** [comment]
@all-contributors please add @MichaelCurrin  for bug

**Comment by MichaelCurrin** [comment]
Thanks. It's a description field not a code change. Otherwise I would have made a PR.

Neat bot!

**Comment by atapas** [comment]
Yes, this is fixed now. Closing.
