### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by MichaelCurrin** [atapas/princess-finder#4]
If you don't include a License file, the default is that your project is protected and may not be copied.

So add `LICENSE` file on GitHub will help you choose.

MIT and Unlicense (no restrictions) are common choices.

**Comment by atapas** [comment]
Hi @MichaelCurrin,

Great, You got this one. I shall fix it up soon. Btw.. Feel free to pick it up for a fix if you would like to.

**Comment by MichaelCurrin** [comment]
I'll make a PR if you indicate a choice of License.

https://choosealicense.com/licenses/

MIT and Unlicense are described at the bottom of that page. The page is ordered from restrictive to permissive (least restrictive).

**Comment by atapas** [comment]
> I'll make a PR if you indicate a choice of License.
> 
> https://choosealicense.com/licenses/
> 
> MIT and Unlicense are described at the bottom of that page. The page is ordered from restrictive to permissive (least restrictive).

MIT sounds great! Please let me know when you have the PR ready.. Yes, you can also fix the typo in the same PR if you want.
